### ISSUE TITLE
Beat saber crashes on launch when mod is enabled

### ISSUE THREAD

**Issue by Maleriandro** [Metalit/PlaylistCore#10]
Crash log:
https://analyzer.questmodding.com/crashes/X12E

I tried disabling, and enabling other mods, but the only thing that makes it work, is disabling playlistCore.

I updated from 1.28, and i backuped, and restored the data (mainly to still have the songs). I am trying to avoid to reinstall the game without the save data, but if its a possible solution, tell me and will try and update you.

**Comment by Metalit** [comment]
It doesn't have anything to do with your save data or with playlistcore either. It's more likely caused by the older version of one of the libraries you have installed, and you can go to the bsmg discord to get help with that.
