### ISSUE TITLE
Playlist order method is case-sensitive so sorting ends up incorrect

### ISSUE THREAD

**Issue by L3Home** [Metalit/PlaylistCore#4]
The order method for playlistConfig (which I wasn't able to locate in a class construct so couldn't dig deeper than the method name being called) is incorrectly sorting song titles in a case-sensitive manner.

This means that songs on the custom playlist end up with all of the capitalized songs at the top (and any all-caps like AJR above those), and songs in all lowercase end up below them. This makes it very difficult to locate songs.

**Comment by Metalit** [comment]
I'm a little confused, where are the playlist songs being sorted here that you're seeing the order be incorrect? They should be in the order defined by the playlist itself, not alphabetized in any way
