### ISSUE TITLE
PlayListManager doesn't seem to allow In-Game Playlist Editing for 1.35

### ISSUE THREAD

**Issue by michaelcatt** [Metalit/PlaylistCore#6]
In the 1.28 version, there were buttons to add or remove a song from a playlist, as well as to create and edit playlists in-game. This functionality no longer seems to be present in the 1.35 version.

**Comment by Metalit** [comment]
That's because it's a different mod that hasn't been updated for 1.35 yet.

**Comment by wblop92** [comment]
May I ask if you have any plans to add this function?Or this function cannot be implemented in the new version?

**Comment by lemmingllama** [comment]
> May I ask if you have any plans to add this function?Or this function cannot be implemented in the new version?

This already exists with the PlaylistManager mod, and that mod is already up to date for 1.37. The original issue here was for a mod that isn't PlaylistCore.
